name: bananagram
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  fluttertoast: ^8.2.4
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  uuid: ^4.5.1
  photo_manager: ^3.7.1
  cached_network_image: ^3.4.1
  auto_size_text_field: ^2.2.4
  lottie: ^3.3.2
  gallery_saver_plus: ^3.2.9
  image_downloader: ^0.31.0
  path_provider: ^2.1.5
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Billabong Regular.ttf
    - assets/images/apes_comment.png
    - assets/images/bananas_like.png
    - assets/images/bananas_like_empty.png
    - assets/images/apes_comme.png
    - assets/animations/Banana.json
    - assets/animations/Banana Animation.json
    - assets/animations/Monkey.json
    - assets/animations/like_banana.json
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong Regular.ttf
